# Generated by Django 6.0.7 on 2026-08-02 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_service'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('INSTRUCTOR', 'Instructor'), ('PARTICIPANTE', 'Participante')], default='PARTICIPANTE', max_length=20, verbose_name='Rol en la plataforma')),
                ('active', models.BooleanField(default=True, verbose_name='Vinculación activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_links', to='institutions.institution', verbose_name='Institución')),
                ('services', models.ManyToManyField(blank=True, related_name='user_links', to='institutions.service', verbose_name='Servicios')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institutional_links', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Vinculación institucional',
                'verbose_name_plural': 'Vinculaciones institucionales',
                'ordering': ['institution', 'user__last_name', 'user__first_name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'institution'), name='unique_user_institution_link')],
            },
        ),
    ]
