# Generated by Django 6.0.7 on 2026-08-02 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_institutionallink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionallink',
            name='role',
        ),
        migrations.AddField(
            model_name='institutionallink',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AddField(
            model_name='institutionallink',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 8, 2), verbose_name='Fecha de inicio'),
            preserve_default=False,
        ),
    ]
