# Generated by Django 6.0.7 on 2026-08-09 20:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0010_trainingassignment_completed_modules_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código de verificación')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='training.trainingassignment', verbose_name='Asignación')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-issued_at'],
            },
        ),
    ]
