# Generated by Django 6.0.7 on 2026-08-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='nit',
            field=models.CharField(max_length=30, unique=True, verbose_name='Número de Identificación Tributaria (NIT)'),
        ),
    ]
