# Generated by Django 6.0.7 on 2026-08-02 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_alter_institution_nit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del servicio')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='institutions.institution', verbose_name='Institución')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subservices', to='institutions.service', verbose_name='Servicio principal')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['institution', 'name'],
                'constraints': [models.UniqueConstraint(fields=('institution', 'name'), name='unique_service_name_per_institution')],
            },
        ),
    ]
