# Generated by Django 6.0.7 on 2026-08-17 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0003_service'),
        ('training', '0010_trainingassignment_completed_modules_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Título')),
                ('document_type', models.CharField(choices=[('PROTOCOL', 'Protocolo'), ('CLINICAL_GUIDE', 'Guía de práctica clínica'), ('PROCEDURE', 'Procedimiento'), ('MANUAL', 'Manual'), ('INSTRUCTION', 'Instructivo'), ('FORMAT', 'Formato'), ('RESOLUTION', 'Resolución'), ('OTHER', 'Otro')], max_length=30, verbose_name='Tipo de documento')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('file', models.FileField(upload_to='resources/documents/', verbose_name='Archivo')),
                ('version', models.CharField(default='1.0', max_length=30, verbose_name='Versión')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Fecha del documento')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_document_resources', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_resources', to='institutions.institution', verbose_name='Institución')),
                ('training_actions', models.ManyToManyField(blank=True, related_name='document_resources', to='training.trainingaction', verbose_name='Acciones de formación')),
            ],
            options={
                'verbose_name': 'Documento institucional',
                'verbose_name_plural': 'Biblioteca documental',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MediaResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Título')),
                ('media_type', models.CharField(choices=[('VIDEO', 'Video'), ('PRESENTATION', 'Presentación'), ('AUDIO', 'Audio'), ('IMAGE', 'Imagen'), ('INFOGRAPHIC', 'Infografía'), ('LINK', 'Enlace'), ('OTHER', 'Otro')], max_length=30, verbose_name='Tipo de recurso')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/media/', verbose_name='Archivo')),
                ('external_url', models.URLField(blank=True, verbose_name='Enlace externo')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_media_resources', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_resources', to='institutions.institution', verbose_name='Institución')),
                ('training_actions', models.ManyToManyField(blank=True, related_name='media_resources', to='training.trainingaction', verbose_name='Acciones de formación')),
            ],
            options={
                'verbose_name': 'Recurso multimedia',
                'verbose_name_plural': 'Biblioteca multimedia',
                'ordering': ['title'],
            },
        ),
    ]
