# Generated by Django 6.0.7 on 2026-08-02 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('code', models.CharField(max_length=30, verbose_name='Código')),
                ('objective', models.TextField(verbose_name='Objetivo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('requires_certificate', models.BooleanField(default=True, verbose_name='Requiere certificado')),
                ('has_validity', models.BooleanField(default=False, verbose_name='Tiene vigencia')),
                ('requires_renewal', models.BooleanField(default=False, verbose_name='Requiere renovación periódica')),
                ('renewal_period_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Período de renovación en meses')),
                ('new_version_requires_retake', models.BooleanField(default=False, verbose_name='Nueva versión obliga a repetir la formación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_types', to='institutions.institution', verbose_name='Institución')),
            ],
            options={
                'verbose_name': 'Tipo de acción',
                'verbose_name_plural': 'Tipos de acción',
                'ordering': ['institution', 'name'],
                'constraints': [models.UniqueConstraint(fields=('institution', 'name'), name='unique_action_type_name_per_institution'), models.UniqueConstraint(fields=('institution', 'code'), name='unique_action_type_code_per_institution')],
            },
        ),
    ]
