# Generated by Django 6.0.7 on 2026-08-02 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_service'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('code', models.CharField(max_length=30, verbose_name='Código')),
                ('objective', models.TextField(verbose_name='Objetivo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versión')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicada'), ('ARCHIVED', 'Archivada')], default='DRAFT', max_length=15, verbose_name='Estado')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_actions', to='training.actiontype', verbose_name='Tipo de acción')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_actions_created', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de la creación')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_actions', to='institutions.institution', verbose_name='Institución')),
            ],
            options={
                'verbose_name': 'Acción de formación',
                'verbose_name_plural': 'Acciones de formación',
                'ordering': ['institution', 'name'],
                'constraints': [models.UniqueConstraint(fields=('institution', 'code'), name='unique_training_action_code_per_institution')],
            },
        ),
    ]
