# Generated by Django 6.0.7 on 2026-08-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingaction',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
    ]
