# Generated by Django 6.0.7 on 2026-08-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_trainingaction_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingaction',
            name='automatic_certificate',
            field=models.BooleanField(default=False, verbose_name='Emisión automática del certificado'),
        ),
        migrations.AddField(
            model_name='trainingaction',
            name='generates_certificate',
            field=models.BooleanField(default=False, verbose_name='Genera certificado'),
        ),
        migrations.AddField(
            model_name='trainingaction',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número máximo de intentos'),
        ),
        migrations.AddField(
            model_name='trainingaction',
            name='passing_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Puntaje mínimo de aprobación'),
        ),
        migrations.AddField(
            model_name='trainingaction',
            name='requires_complete_content',
            field=models.BooleanField(default=True, verbose_name='Requiere completar todo el contenido'),
        ),
        migrations.AddField(
            model_name='trainingaction',
            name='requires_final_evaluation',
            field=models.BooleanField(default=False, verbose_name='Requiere evaluación final'),
        ),
        migrations.AddField(
            model_name='trainingaction',
            name='requires_pretest',
            field=models.BooleanField(default=False, verbose_name='Requiere pretest'),
        ),
    ]
