# Generated by Django 6.0.7 on 2026-08-02 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_trainingaction_automatic_certificate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingaction',
            name='mandatory',
            field=models.BooleanField(default=True, verbose_name='Obligatoria'),
        ),
        migrations.CreateModel(
            name='TrainingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha límite')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En progreso'), ('APPROVED', 'Aprobada'), ('NOT_APPROVED', 'No aprobada'), ('EXPIRED', 'Vencida')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_assignments_created', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de la asignación')),
                ('training_action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='training.trainingaction', verbose_name='Acción de formación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Asignación de capacitación',
                'verbose_name_plural': 'Asignaciones de capacitación',
                'ordering': ['-assigned_at'],
                'constraints': [models.UniqueConstraint(fields=('training_action', 'user'), name='unique_training_action_assignment_per_user')],
            },
        ),
    ]
