# Generated by Django 6.0.7 on 2026-08-02 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_trainingaction_mandatory_trainingassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingaction',
            name='html_content',
            field=models.FileField(blank=True, help_text='Cargue un archivo HTML que contenga el contenido principal de la capacitación.', null=True, upload_to='training/html/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html', 'htm'])], verbose_name='Contenido HTML principal'),
        ),
    ]
