# Generated by Django 6.0.7 on 2026-08-03 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_trainingaction_html_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingaction',
            old_name='html_content',
            new_name='learning_content',
        ),
    ]
