# Generated by Django 6.0.7 on 2026-08-07 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_rename_html_content_trainingaction_learning_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pretest_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Puntaje pretest')),
                ('posttest_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Puntaje postest')),
                ('improvement_points', models.IntegerField(blank=True, null=True, verbose_name='Mejora en puntos')),
                ('approved', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1, verbose_name='Número de intento')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de finalización')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='training.trainingassignment', verbose_name='Asignación')),
            ],
            options={
                'verbose_name': 'Resultado de capacitación',
                'verbose_name_plural': 'Resultados de capacitación',
                'ordering': ['-completed_at'],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'attempt_number'), name='unique_training_result_attempt')],
            },
        ),
    ]
