# Generated by Django 6.0.7 on 2026-08-07 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_trainingresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingresult',
            options={'ordering': ['assignment'], 'verbose_name': 'Resultado de capacitación', 'verbose_name_plural': 'Resultados de capacitación'},
        ),
        migrations.RemoveConstraint(
            model_name='trainingresult',
            name='unique_training_result_attempt',
        ),
        migrations.AlterField(
            model_name='trainingresult',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='training.trainingassignment', verbose_name='Asignación'),
        ),
        migrations.AlterField(
            model_name='trainingresult',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Intentos de postest utilizados'),
        ),
        migrations.AlterField(
            model_name='trainingresult',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='trainingresult',
            name='posttest_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mejor puntaje postest'),
        ),
        migrations.AlterField(
            model_name='trainingresult',
            name='pretest_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Puntaje pretest inicial'),
        ),
    ]
