# Generated by Django 6.0.7 on 2026-08-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_alter_trainingresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingassignment',
            name='completed_modules',
            field=models.JSONField(blank=True, default=list, verbose_name='Módulos completados'),
        ),
        migrations.AddField(
            model_name='trainingassignment',
            name='current_module',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Módulo actual'),
        ),
        migrations.AddField(
            model_name='trainingassignment',
            name='progress_stage',
            field=models.CharField(choices=[('PRETEST', 'Pretest'), ('CONTENT', 'Contenido'), ('POSTTEST', 'Postest'), ('COMPLETED', 'Finalizada')], default='PRETEST', max_length=15, verbose_name='Etapa actual'),
        ),
    ]
